Step3 pr합니다.
code-squad/java-coordinate pull request #136
Opened 2019-01-13 10:10 UTC by LYJr

Rectangle 객체를 만들었다가 사용을 하지 않아서 삭제하였습니다.
Interface 적용할 때 다시 생성하여 적용하겠습니다.

ResultView에서 출력하다보니 매개변수가 늘어나고 있는걸
어떻게 해야 줄일 수 있을지 모르겠습니다.

피드백 부탁드리겠습니다 :)

2019-01-13 10:42 UTC, javajigi requested changes
Line 객체를 적극 활용해 구현한다.

2019-01-13 10:42 UTC, javajigi commented on src/main/java/coordinates/view/ResultView.java
> +        // TODO: 매개변수를 줄일 방법이 없을까?
rectangle로 시작하는 메소드를 Rectagle 객체에 구현한다.

2019-01-13 10:42 UTC, javajigi commented on src/main/java/coordinates/view/ResultView.java
>      public static void graphWidthLin(List<Point> points, List<Integer> reversalAxis, List<Integer> axis) {
메소드 이름을 graphWidthLine으로 수정
`List<Point> points` 대신 Line 객체를 사용하면 어떨까?

2019-01-13 10:42 UTC, javajigi commented on src/main/java/coordinates/MainController.java
> +        ResultView.mathLine(points, mainControllerUtil.areaAndLength(points));
Line 객체를 추가했는데 사용하지 않나?

2019-01-17 07:47 UTC, parkjaesung commented on src/main/java/rentcompany/domain/RentCompany.java
> +    private List<String> name = new ArrayList<>();
Car 목록이 있는데 굳이 name의 목록이 필요한가?
데이터의 중복이다. name 목록 없이 구현해본다.

2019-01-17 07:48 UTC, javajigi commented on src/main/java/rentcompany/domain/RentCompany.java
> +    private List<String> name = new ArrayList<>();
Car 목록이 있는데 굳이 name의 목록이 필요한가?
데이터의 중복이다. name 목록 없이 구현해본다.

2019-01-21 08:36 UTC, closed without merging