Step4
code-squad/java-coordinate pull request #21
Opened 2018-03-22 04:42 UTC by imjinbro

## 구현
1. 구조 변경 : Figure > Triangle, Rectangle (상속해야할 부분이 보여서 묶어서 구현했습니다)
2. 도형 팩토리 클래스 추가
3. 삼각형 넓이 기능 구현 : 라인 활용
4. 삼각형, 구조 관련 테스트 코드 추가
5. 유효 좌표 개수 로직 enum 에서 처리하도록 변경

2018-03-22 05:14 UTC, javajigi requested changes
추상 클래스 추출하고 중복되는 부분을 제거 잘 했네. good.

2018-03-22 05:14 UTC, javajigi commented on src/main/java/Main.java
> +        if (Line.VALID_COORDINATE_NUM == pointRepo.getSavedSize()) {
pointRepo.isValid(Line.VALID_COORDINATE_NUM)와 같이 구현하면 어떨까?

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/figure/FigureCreator.java
> +        if (Triangle.VALID_COORDINATE_NUM == pointRepo.getSavedSize()) {
pointRepo.isValid(Triangle.VALID_COORDINATE_NUM)

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/figure/FigureCreator.java
> +public class FigureCreator {
Creator도 좋은데 오전에 이야기한 Factory라는 이름도 많이 사용함.

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/Line.java
> +        this(createPoints(aSidePoint, bSidePoint));
api 사용자 편의성을 위해 생성자 추가한 것 💯

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/Line.java
> +        pointRepo.addPoint(aSidePoint.getXPosition(), aSidePoint.getYPosition());
굳이 Point의 값을 추출한 후 다시 Point로 바꿔야할까?
그냥 Point 자체를 add 한다.

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/figure/Figure.java
> +    public abstract String getFigureName();
추상 클래스 구현 👍

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/figure/Figure.java
> +    Points pointRepo;
private으로 변경해 구현할 수 있을까?

2018-03-22 05:14 UTC, javajigi commented on src/main/java/domain/figure/Rectangle.java
> +        double length = getDiffPosition(points, Point::getXPosition);
두 점의 거리를 구하는 로직은 여러 곳에서 공통으로 사용됨.
다음과 같은 구현은 어떨까?

```
double length = point.getLength(otherPoint);
```

2018-03-23 01:30 UTC, javajigi requested changes
작은 피드백 몇 개 남겼다. 금방 해결할거야.

2018-03-23 01:30 UTC, javajigi commented on src/test/java/domain/figure/RectangleTest.java
> +        );
List<Point> points = Arrays.asList(new Point(22, 18), new Point(10, 10), new Point(10, 18), new Point(22, 10));

위와 같이 구현 가능함. 앞으로도 new ArrayList로 다시 생성하지 말고 위와 같이 구현해라. 다른 부분도 모두 바꿔라.

2018-03-23 01:30 UTC, javajigi commented on src/main/java/domain/point/Point.java
> +        double xDiffSquare = calcDiffSquare(this.xPosition, otherPoint.getXPosition());
otherPoint.xPosition으로 구현 가능함. get() 메소드 쓰지 않아도 됨.

2018-03-23 01:32 UTC, imjinbro commented on src/main/java/domain/point/Point.java
> +        double xDiffSquare = calcDiffSquare(this.xPosition, otherPoint.getXPosition());
다른 포인트 객체에 요청한다는 의미로 get 메소드를 사용했는데, 인스턴스.상태값 이렇게 해도 같은 의미로 해석해도 되나요?

2018-03-23 01:44 UTC, javajigi commented on src/main/java/domain/point/Point.java
> +        double xDiffSquare = calcDiffSquare(this.xPosition, otherPoint.getXPosition());
나는 get을 쓰나 필드에 직접 접근하나 같을 것 같다고 생각하는데 네가 다르게 생각한다면 너의 생각대로 구현해라. 나는 이 방식도 가능하다는 것을 이야기하고 싶었음.

2018-03-23 01:48 UTC, imjinbro commented on src/main/java/domain/point/Point.java
> +        double xDiffSquare = calcDiffSquare(this.xPosition, otherPoint.getXPosition());
넵 알겠습니다~! 이부분에 대해 나름대로의 기준을 생각해봐야겠습니다

2018-03-23 02:12 UTC, merged