Step3
code-squad/java-coordinate pull request #23
Opened 2018-03-22 08:16 UTC by krapeaj

2018-03-22 09:16 UTC, javajigi requested changes
새로운 객체를 도출해보고 해당 객체에 관련 로직을 적절히 구현하도록 리팩토링해보면 좋겠네요.

2018-03-22 09:16 UTC, javajigi commented on src/main/java/coordinate/domain/Points.java
> +        checkSquare(points);
Point는 점 하나를 의미하는데 여기서 square인지를 체크하는 것은 뭔가 좀 맞지 않는 것 같다.
이 로직을 구현할 적절한 곳을 찾아보면 좋겠다.

2018-03-22 09:16 UTC, javajigi commented on src/test/java/coordinate/domain/PointsTest.java
> +        Point p1 = new Point(new int[]{0, 0});
Point를 생성할 때 배열보다 Point(int x, int y)가 더 낫지 않을까?

2018-03-22 09:16 UTC, javajigi commented on src/test/java/coordinate/domain/UtilsTest.java
> +    }
두 점을 입력하는 step2는 Line, 네 점을 입력하는 사각형은 Square와 같은 객체를 추가하고 각 객체의 역할에 맞는 로직을 구현해 보면 좋겠음.

2018-03-22 09:31 UTC, krapeaj commented on src/test/java/coordinate/domain/PointsTest.java
> +        Point p1 = new Point(new int[]{0, 0});
(x,y)를 받아서 혹시 사용자가 (z,y,z)와 같이 입력했을 때를 예외처리하려고 하다보니..

2018-03-23 12:08 UTC, javajigi requested changes
마지막 피드백이 될 것 같다. 객체를 좀 더 활용했으면 하는 바람으로 피드백 몇개 남긴다.

2018-03-23 12:08 UTC, javajigi commented on src/main/java/coordinate/domain/Line.java
> +    }
List<Point>를 생성자의 인자로 전달하고 인스턴스 변수로 구현한다면 어떨까?
지금 구현한 코드와 어떻게 달라질지 고민해 보고 더 나은 방법을 찾아보면 좋겠다.

2018-03-23 12:08 UTC, javajigi commented on src/main/java/coordinate/domain/Line.java
> +        double ySquared = Math.pow(points.get(FIRST_POINT).getY() - points.get(SECOND_POINT).getY(), 2);
두 점 사이의 거리를 다음과 같이 구현한다면..

`point.calculateDistance(otherPoint);`와 같이 구현하는 것과 위와 같이 구현하는 것 중 어느 것이 더 나을까? 값을 get하지 않도 객체에 메시지를 보내라는 원칙으로 구현해 본다.

2018-03-23 12:08 UTC, javajigi commented on src/main/java/coordinate/domain/Shape.java
> +}
오호. 추상 클래스까지 추가 👍

2018-03-26 06:18 UTC, javajigi requested changes
이전 코드보다 구현 잘 했네. 작은 피드백 몇 개 남긴다.

2018-03-26 06:18 UTC, javajigi commented on src/main/java/coordinate/domain/CoordinateCalculator.java
> +        if (match) {
이미 상속을 사용하고 있다면 위와 같이 구현할 필요 없이 바로 다음과 같이 구현 가능하지 않을까?
앞의 10라인 정도가 의미가 없어보임.

```
if (shape.isMatch(x, y)) {
}
```

2018-03-26 06:18 UTC, javajigi commented on src/main/java/coordinate/domain/Line.java
> +    private Line(List<Point> points) {
points.size()가 2인지를 체크해야 되지 않을까?

2018-03-26 06:55 UTC, merged