Step2
code-squad/java-coordinate pull request #27
Opened 2018-03-23 07:06 UTC by david-learner

2018-03-23 08:51 UTC, javajigi requested changes
객체 분리를 잘 하기는 했는데 한 단계 더 도전해 보면 좋겠다.

2018-03-23 08:51 UTC, javajigi commented on src/main/java/domain/CoordinateCalculator.java
> +        return calculatePoints(a, b);
point.getDistance(otherPoint)와 같이 구현하는 것은 어떨까?
어느 것이 나을까?

2018-03-23 08:51 UTC, javajigi commented on src/main/java/domain/Line.java
> +public class Line {
Line 이라면 두 점을 가져야하지 않을까?
Line의 길이를 구하는 로직도 이곳에 있고..

new Line(Point a, Point b); 와 같은 구조도 되고, 관련 로직을 이곳에서 처리하는 것이 더 명확하지 않을까?

2018-03-23 08:51 UTC, javajigi commented on src/main/java/domain/Point.java
> +    public static ArrayList<Point> makePoints(List<String> numbers) {
Point인데 Point 하나만 생성해야지 여러 개의 Point를 생성하는 것은 적합하지 않아 보임.
Point 자신만을 생성하도록 구조를 변경해 본다.

2018-03-23 08:51 UTC, javajigi commented on src/main/java/domain/Point.java
> +    public Point(int x, int y) {
x, y의 값이 유효 범위를 벗어나는지에 대한 체크해야 되지 않을까?

2018-03-23 08:51 UTC, javajigi commented on src/main/java/domain/Line.java
> +        this.marks = new ArrayList<>(Collections.nCopies(24, false));
굳이 24의 모든 점에 대한 정보를 가지고 있어야 되나?
좌표 크기가 커지면 성능상 좋지 않겠다.

2018-03-23 10:48 UTC, david-learner commented on src/main/java/domain/Point.java
> +    public Point(int x, int y) {
포비, 사용자가 좌표를 입력하는 단계(InputView)에서 유효성 체크를 하는 것보다 Point를 생성할 때(new Point(x, y)) 유효성 체크를 하는 것이 더 자연스럽다는 말씀이신가요??

2018-03-23 11:59 UTC, javajigi commented on src/main/java/domain/Point.java
> +    public Point(int x, int y) {
Point에서 유효성 체크를 하면 잘못된 Point가 생성되는 경우를 원천적으로 막을 수 있기 때문에 더 안전한 코드를 구현할 수 있다. 그러면 굳이 사용자 입력 단계에서 체크하지 않아도 된다.

2018-03-24 23:15 UTC, javajigi requested changes
힘들게 구현한 것 같은데 피드백 몇개 남긴다.

2018-03-24 23:15 UTC, javajigi commented on src/main/java/domain/CoordinateBase.java
> +        points = new ArrayList<>();
굳이 ArrayList를 생성할 필요는 없지 않을까?

2018-03-24 23:15 UTC, javajigi commented on src/main/java/domain/Line.java
> +    Double length;
인스턴스 변수로 구현하지 않는다.
getDistance 메소드를 호출할 때 length를 구해 바로 반환한다.
굳이 인스턴스 변수로 구현할 필요 없음.

2018-03-24 23:15 UTC, javajigi commented on src/main/java/domain/Line.java
> +    Point b;
인스턴스 변수는 특별한 이유가 없는한 private으로 구현한다.

2018-03-24 23:15 UTC, javajigi commented on src/main/java/domain/Line.java
> +        this.length = Math.sqrt(Math.pow((aX - bX), 2) + Math.pow((aY - bY), 2));
point.getDistance(otherPoint);와 같이 길이를 구하는 로직을 Point에 위임하면 어떨까?
지금 코드와 어느 코드가 나을지 고민해 본다.

2018-03-24 23:15 UTC, javajigi commented on src/main/java/domain/ShapeController.java
> +
사용하지 않는 코드는 제거한다.

2018-03-24 23:15 UTC, javajigi commented on src/main/java/domain/CoordinateBase.java
> +        return pointsList;
이곳의 코드가 상당히 복잡함.
꼭 이와 같이 복잡하게 구현해야 하나? 좀 더 쉬운 방법은 없을까?

2018-03-25 09:44 UTC, david-learner commented on src/main/java/domain/Line.java
> +        this.length = Math.sqrt(Math.pow((aX - bX), 2) + Math.pow((aY - bY), 2));
Point라는 객체에게 다른 Point와 길이가 얼마야?라고 묻는다고 생각하니, 포비 말씀이 맞는 것 같습니다.

2018-03-26 00:30 UTC, merged