file copy and paste
code-squad/java-coordinate pull request #28
Opened 2018-03-23 07:21 UTC by LarryJung

step4 구현해보았습니다.
책에서 본 factory클래스를 사용해 보았습니다.

2018-03-23 08:56 UTC, javajigi requested changes
Fractory 클래스 추가 좋네. 그런데 Figure 객체를 분리했으면 각 객체에 맡는 책임을 더 철저히 분리해 보면 좋겠다.

2018-03-23 08:56 UTC, javajigi commented on src/main/java/domain/FigureFactory.java
> +        return coordinates.size() == 2;
이 상수 값들을 각 Figure가 가지거나 isLine, isTriangle이 각 Figure에 구현된다면..
어느 곳에 있는 것이 나을까?

2018-03-23 08:56 UTC, javajigi commented on src/main/java/domain/Points.java
>          return calculateLineBwPoints(points.get(0), points.get(1));
이 메소드를 다음과 같이 구현해 본다.

points.calculateLineBwPoints(0, 1);

이와 같이 구현한다면.. 어떻게 구현하는 것이 나을까?

2018-03-23 08:56 UTC, javajigi commented on src/main/java/domain/Triangle.java
> +        super.area = super.points.calculateTriangle();
Triangle과 관련한 로직을 points에서 처리하는 이유는?
이 객체 내에서 처리해야 하지 않을까?

2018-03-25 21:08 UTC, LarryJung commented
1. Figure를 추상화를 명확하게 하고 싶어서, 기존에 Figure 안에 있던 factory class를 figureMaker에서 그 역할을 하게 바꿨고,
2. FigureMaker클래스도 추상클래스여서 추상화 객체끼리 interaction하게 해봤습니다만..(디자인 패턴을 보면서 하려고 했으나 맞게 응용한 건지 잘 모르겠습니다 ㅠ)
3. 기존 points에서 넓이를 구하는 로직을 각 Figure sub class 안에서 구현되도록 수정하였습니다.

추상클래스를 객체화 할 수 없다는 점 때문에 생각보다 애먹었던 것 같습니다 ㅠㅠ

2018-03-26 07:08 UTC, merged