Step2
code-squad/java-coordinate pull request #29
Opened 2018-03-23 12:41 UTC by sarguments

구현시간이 너무 오래걸렸네요.. ㅠㅠ

요구사항 분석하는 법 강의를 듣고싶습니다.

2018-03-23 22:40 UTC, javajigi requested changes
요구사항 분석하는데 어려움이 있었다고 하는데 코드 구현한 것 보니 잘 구현했네. 시간이 좀 걸렸지만 코드는 확실히 객체지향스럽게 구현했다.

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/CoordinateMain.java
> +        Input userInput = new Input();
Input과 Output과 같은 클래스들은 굳이 인스턴스를 생성할 필요는 없겠다.
Scanner도 static으로 생성한 후 클래스 메소드로 구현해도 되지 않을까?

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/CoordinateMain.java
> +        System.out.println(coordinateCalc.calcProc());
이 두 라인도 Output의 메소드로 구현해도 되지 않을까?

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/CoordinateMain.java
> +        Output output = new Output(coordinateCalc.getRowLines());
```
output.printResult(coordinateCalc);
```

main() 에서는 이 한줄로 끝내고 printResult 내부에서 아래 구현을 하는 것도 좋겠다.

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/CoordinateCalc.java
> +    }
생성자는 인스턴스 변수 아래에 구현하는 것이 관례

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/CoordinateCalc.java
> +import static saru.view.Output.MAX_VALUE;
domain 로직 구현에서 view 값을 참조하는 것은 추천하지 않음.
domain에 상수 값을 가지는 것이 낫겠다.

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/CoordinateCalc.java
> +        return userInput.get(FIRST_INDEX).calcLengthWith(userInput.get(SECOND_INDEX));
RowLine 말고 두 점을 가지는 Line 객체를 추가.
Line 객체에서 두 점 사이의 거리를 구하는 메소드를 가지면 어떨까?

`new Line(List<Point> userInput)`과 같이 생성..

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/CoordinateCalc.java
> +        foundPoint.draw();
이런 코드는 👍

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/CoordinateCalc.java
> +            drawPoint((int) point.getX(), (int) point.getY());
굳이 x, y 값을 꺼내지 말고 그냥 Point로 전달해 구현.

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/Point.java
> +    }
이 메소드 구현은 객체를 제대로 활용해 구현했네 💯

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/domain/RowLine.java
> +            points.add(new Point(i, nowRow, false));
false 값은 굳이 인자로 전달하지 말고 Point 내의 기본 값을 false로 하면 더 낫지 않을까?
또는 factory method를 만들거나?

2018-03-23 22:40 UTC, javajigi commented on src/main/java/saru/view/Input.java
> +            return 1;
이 유효성 체크하는 부분을 Point 객체가 담당하도록 구현할 수는 없을까?

2018-03-23 22:40 UTC, javajigi commented on src/test/java/saru/CoordinateCalcTest.java
> +}
Point의 거리 계산이나 draw 메소드 등도 테스트가 필요한 좋은 코드이다.
이 코드도 테스트 추가하면 좋겠다.

2018-03-24 23:19 UTC, javajigi requested changes
반드시 알아야할 내용이 있어 피드백 하나 남긴다.

2018-03-24 23:19 UTC, javajigi commented on src/main/java/saru/domain/Point.java
> +        this.isExist = false;
이 생성자는 유효성 처리가 되지 않고 있음.
따라서 이 경우 다음과 같이 구현해야 함.

`this(x, y, false);`와 같이 구현해 예외 처리를 하고 있는 자신의 다른 생성자를 호출하도록 구현하면 됨.

2018-03-24 23:48 UTC, sarguments commented on src/main/java/saru/domain/Point.java
> +        this.isExist = false;
아. 세세하게 신경을 쓰지 못했네요. 잘 숙지하겠습니다

2018-03-25 00:01 UTC, merged