step5
code-squad/java-coordinate pull request #34
Opened 2018-03-26 07:42 UTC by durin93

step5 구현해보았습니다.

2018-03-26 09:12 UTC, javajigi requested changes
적지만 의미있는 경험을 하리라 믿으면 피드백 남겨요.

2018-03-26 09:12 UTC, javajigi commented on src/main/java/coordinate/domain/Figure.java
> +	public ArrayList<Point> points;
private 접근 제어자로 만들고 구현해 본다.

2018-03-26 09:12 UTC, javajigi commented on src/main/java/coordinate/domain/Point.java
>  		for (int i = 0; i < points.length; i++) {
Point 하나를 의미한다면 굳이 for문을 돌어야 되나?
points.length를 바로 체크하면 안되나?

2018-03-26 20:45 UTC, durin93 commented
추상클래스 figure클래스에서 
변수를 private 접근지정자를 사용해서 구현해보라고하셨는데,
private을 사용하면 해당클래스에서만 사용이가능하기때문에
자식클래스에서 부모클래스의 생성자를 호출하는방식으로 해당필드에 값을주고
get메서드를통해 값을 가져오는 형태로 구현을 해보았는데,
이렇게 하니 뭔가 get get이 많이보여서 잘못한거같은데,
혹시 이런식으로 하는게 맞는것인지 궁금합니다 ㅎㅎ

2018-03-27 01:38 UTC, javajigi requested changes
구현 잘 했네. 네가 구현한대로 get 메소드 활용하면 된다. 그런데 가능하면 get 메소드도 추가하지 않고 구현할 수 있으면 더 좋고, 만약 힘들다면 지금처럼 get을 통해 접근하도록 하고, 자식에서만 사용한다면 protected 접근 제어자로 제한할 수 있다.

2018-03-27 01:38 UTC, javajigi commented on src/main/java/coordinate/domain/Figure.java
> +	}
각 위치에 따른 point를 접근할 수 있는 메소드가 있는데 굳이 모든 Point를 노출할 필요가 있나?

2018-03-27 01:38 UTC, javajigi commented on src/main/java/coordinate/domain/Triangle.java
> +		double c = super.getPoint(2).getDistance(super.getPoint(0));
반드시 super를 쓰지 않아도 된다.
거리 구하는 메소드 자체를 부모로 이동하면 어떨까?
자식은 거리를 구하고자하는 Point의 위치 정보만 전달하고..

2018-03-27 02:11 UTC, durin93 commented on src/main/java/coordinate/domain/Triangle.java
> +		double c = super.getPoint(2).getDistance(super.getPoint(0));
피드백 주신데로 수정하고, 거리구하는 메서드자체를 부모로 이동시켜봤는데여.
삼각형의 경우 코드가 깔끔해졌는데
사각형의 경우 지금  
if (line.isSameYaxis()) {
height = line.getDistance();
} 이코드가
if (getPoint(i).isSameXaxis(getPoint(j))) {
height = getDistance(i, j);
}
이렇게 바뀌게되었는데여, 뭔가 좀더 지저분해진것같아서요.
조언 부탁드립니다. 머지해주셔도 감사합니다 


그리고어제 어쩌다보니 밤을새서 오늘은 집에서 열심히코딩을하도록하겠씁니다..ㅋㅋ

2018-03-27 02:14 UTC, durin93 commented
피드백 주신데로 수정하고, 거리구하는 메서드자체를 부모로 이동시켜봤는데여.
삼각형의 경우 코드가 깔끔해졌는데
사각형의 경우 지금
if (line.isSameYaxis()) {
height = line.getDistance();
} 이코드가
if (getPoint(i).isSameXaxis(getPoint(j))) {
height = getDistance(i, j);
}
이렇게 바뀌게되었는데여, 뭔가 좀더 지저분해진것같아서요.
조언 부탁드립니다. 머지해주셔도 감사합니다

그리고어제 어쩌다보니 밤을새서 오늘은 집에서 열심히코딩을하도록하겠씁니다..ㅋㅋ

2018-03-27 02:20 UTC, merged